### ISSUE TITLE
Improve the precision of the return coordinates

### ISSUE THREAD

**Issue by pickled-pepper-pig** [showlab/ShowUI#23]
I have a problem now, my image pixel is about 2000 * 4000, now want to find a button in the image, I observed now the return accuracy is two decimal points, if directly with the return value times the image width, height, the value and the actual button position will be deviation, is there any way to improve the accuracy of the return value to three decimal places

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ShowUIImageProcessor class to handle large images with higher precision. Updated the smart_resize function to use float values instead of integers for more accurate scaling. Adjusted the preprocess method to work with these higher precision values.

You can review changes in this commit: https://github.com/wwqwq2313/showlab-ShowUI-23/commit/9edf31881beaa55d4d75b000edc89f9026856727.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by pickled-pepper-pig** [comment]
Thanks for replying! I have tried your ShowUIImageProcessor class, it seems to have some errors.

Traceback (most recent call last):
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask/app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask/app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Wei/workbench/autoTest/AppConchAutoTestCV/app.py", line 20, in analyse_page
    generated_img_url, coordinate = find_target_point(image_path, query)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Wei/workbench/autoTest/AppConchAutoTestCV/process.py", line 107, in find_target_point
    generated_ids = model.generate(**inputs, max_new_tokens=128)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/transformers/generation/utils.py", line 2009, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/Users/apple/miniconda3/envs/showui/lib/python3.12/site-packages/transformers/generation/utils.py", line 1388, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['patch_pos', 'patch_assign', 'patch_assign_sep', 'patch_assign_len'] (note: typos in the generate arguments will also show up in this list)

**Comment by QinghongLin** [comment]
@pickled-pepper-pig Hi, for improve the accuracy, I think one way is using iterative grounding as shown in this gradio demo: 
https://huggingface.co/spaces/showlab/ShowUI
You can refer the code here:
https://huggingface.co/spaces/showlab/ShowUI/blob/main/app.py#L93

While for our preprocessor,
can you please first try this, which connect Qwen2-VL weight in ShowUI for token selection
https://github.com/showlab/ShowUI/blob/main/test.ipynb 

I am still working with improve and integrate the codes, stay tuned for more updates!
